config/routes.rb
Rails.application.routes.draw do

  get '/user', to: 'users#index'

  get '/group/new', :as => :group_new
  get '/group/:id', to: 'group#show', :as => :group
  get '/group/:id/invite', to: 'group#invite'
  get '/group/:id/enter', to: 'group#enter'
  post '/group/create', to: 'group#create'
  post '/group/:id/create_guest', to: 'group#create_guest', :as => :create_guest

  devise_for :user
  root 'home#index'

  namespace :api, format: 'json' do
    namespace :v1  do
      resources :tickets
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :members
  has_many :users, through: :members
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :ticket
end

app/models/priority.rb
class Priority < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :member, foreign_key: 'assign_to'
  belongs_to :state
  belongs_to :priority
end

app/models/user.rb
class User < ApplicationRecord
  has_many :members
  has_many :groups, through: :members
  has_many :ticket
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["phone_number = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def member(group_id)
    member = self.members.find_by(:group_id => group_id)
  end

end

app/controllers/api/v1/tickets_controller.rb
class Api::V1::TicketsController < ApplicationController
  def index
    @data = Ticket.all.order("updated_at desc")
    @data = @data.where(assign_to: params[:assign_to]) unless params[:assign_to].blank?
  end

  def create
    @ticket = Ticket.create(create_ticket_params)
    render :json => @ticket, status: :created
  end

  def update
    render :json => {:message => "見つかりませんでした"}, status: 404 if params[:id].nil? or not Ticket.exists?(params[:id])
    @ticket = Ticket.find(params[:id])
    @ticket.update(update_ticket_params)
    render :json => @ticket, states: :updated
  end

  private

  def create_ticket_params
    permited = params.permit(:group_id, :assign_to, :title, :body, :state_id, :priority_id, :deadline, :created_by)
    permited[:number] = Ticket.where(:group_id => permited[:group_id]).count + 1
    permited
  end

  def update_ticket_params
    params.permit(:assign_to, :title, :body, :state_id, :priority_id, :deadline)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    session[:user_return_to] || '/user'
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] },:name, :email, :phone_number, :password, :password_confirmation)
    end
  end
end

app/controllers/group_controller.rb
class GroupController < ApplicationController
  before_action :authenticate_user!
  def show
    return unless authenticate_group!
    @waiting_members = Group.find(params[:id]).users.select('*').where('members.is_accept = 0')
    @all_members = Group.find(params[:id]).users.select('*').where('members.is_accept = 1')
    @members = Group.find(params[:id]).users.select('*').where.not(id: current_user.id).where('members.is_accept = 1')
    redirect_to "/group/#{params[:id]}/invite" and return if @all_members.length <= 1 and @waiting_members.empty?
    @states = State.all
    @priorities = Priority.all
    @group = Group.find(params[:id])
    @all_tickets = Ticket.where(:group_id => params[:id]).order("updated_at DESC")
    render :layout => 'app_2column'
  end

  def new
    @group = Group.new
  end

  def create
    @group  = Group.create(params.require(:group).permit(:name))
    @member = @group.members.create(:group_id => @group.id, :user_id => current_user.id, :is_admin => true)
    if @group and @member
      redirect_to "/group/#{@group.id}", notice: "グループを登録しました。"
    else
      redirect_to "/group/new", notice: "グループを作成できませんでした"
    end
  end

  def invite
    authenticate_group!
    @group = Group.find(params[:id])
    @message = "#{@group.name}に招待されました！%0D%0A以下にアクセスして承認してください(*´∇｀*)%0D%0Ahttp://192.168.11.6/group/#{@group.id}/enter"
  end

  def enter
    @group = Group.find(params[:id])
    @members = @group.users
    redirect_to "/group/#{@group.id}" if @members.exists?(id: current_user.id)
  end

  def create_guest
    @group = Group.find(params[:id])
    @members = @group.users.select('*')
    if @members.exists?(:users => {id: current_user.id})
      redirect_to "/group/#{@group.id}" and return
    end
    @member = @group.members.create(:group_id => @group.id, :user_id => current_user.id, :is_accept => false)
    if @member
      redirect_to "/group/#{@group.id}"
    else
      redirect_to "/group/#{@group.id}", notice: "失敗しました"
    end
  end

private
  def authenticate_group!
    @members = Group.find(params[:id]).users.select('*')
    @user = @members.where(id: current_user.id)
    if @user.empty?
      redirect_to "/user", alert: "グループの権限がありません"
      return false
    end
    if @user.first.is_accept == 0
      redirect_to "/user", alert: "承認待ちです。しばらくお待ちください"
      return false
    end
    true
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to '/user'
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  def index
    @groups = current_user.groups.all
    redirect_to '/group/new' if @groups.empty?
  end
end

app/helpers/api/v1/tickets_helper.rb
module Api::V1::TicketsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/elements/_alerts.html.erb
<div class="alert alert-warning" role="alert" id="created-alert" style="display:none">
  <strong>チケットを作成しました</strong>
</div>
<div class="alert alert-warning" role="alert" id="updated-alert" style="display:none">
  <strong>チケットを更新しました</strong>
</div>

app/views/group/enter.html.erb
<h2><%= @group.name %>に入室</h2>

<h3>ゲストとして入る</h3>
<%= form_tag create_guest_path do %>

  <%= hidden_field :group_id, @group.id %>

  <div class="actions">
    <%= submit_tag "ノックする" %>
  </div>
<% end %>

app/views/group/invite.html.erb
<h3><%= @group.name %>に招待しましょう</h3>
<a href="http://line.me/R/msg/text/?<%= @message %>">
  <img src="/assets/sns/line_btn.png">
</a>

app/views/group/new.html.erb
<h3>グループを作りましょう</h3>
<%= form_for @group, :url => {:action => :create} do |f| %>

  <div class="field">
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit "登録する" %>
  </div>
<% end %>

app/views/group/show.html.erb
<%= render 'elements/alerts' %>

<div class="ticket-box">
  <%= react_component(
    'TicketBox',
    url_get: Settings.url.api.v1.ticket.get,
    url_create: Settings.url.api.v1.ticket.create,
    url_update: Settings.url.api.v1.ticket.update,
    group: @group,
    members: @members,
    all_members: @all_members,
    all_tickets: @all_tickets,
    current_member: @current_user.member(@group.id),
    states: @states,
    priorities: @priorities,
  ) %>
</div>

app/views/home/index.html.erb
<div class="mainbody">
  <div class="heading">
    <div class="header-msg">
      <h1>
        家族のお仕事　みんなで管理
      </h1>
      <p>
        sitotteで、家のお仕事をみんなで共有。<br>
        お仕事を簡単に分担・依頼・整理できます。
      </p>
    </div>
    <div class="header-img">
      <img src="/images/bg_top.jpg" alt="top-img">
    </div>
  </div>
</div>

app/views/layouts/app_2column.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sitotte" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-*.min.js"></script>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top navbar-static-top header-menu">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Sitotte</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row hide-overflow">
          <div class="main-sidebar">
            <h3><%= @group.name %></h3>
              <ul class="nav nav-pills nav-stacked">
                <li class="active">
                    <a href="#user-tab<%= current_user.id %>" data-toggle="tab"><%= current_user.name %></a>
                </li>
                <hr>
                <% @members.each do |user| %>
                  <li>
                    <a href="#user-tab<%= user.id %>" data-toggle="tab"><%= user.name %></a>
                  </li>
                <% end %>
              </ul>
          </div><!--/.well -->
        <div class="main-content">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sitotte" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Sitotte</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <%= bootstrap_flash %>
        <%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :email %>
  <%= error_span(@user[:email]) %>
  <%= f.input :encrypted_password %>
  <%= error_span(@user[:encrypted_password]) %>
  <%= f.input :reset_password_token %>
  <%= error_span(@user[:reset_password_token]) %>
  <%= f.input :reset_password_sent_at %>
  <%= error_span(@user[:reset_password_sent_at]) %>
  <%= f.input :remember_created_at %>
  <%= error_span(@user[:remember_created_at]) %>
  <%= f.input :current_sign_in_at %>
  <%= error_span(@user[:current_sign_in_at]) %>
  <%= f.input :last_sign_in_at %>
  <%= error_span(@user[:last_sign_in_at]) %>
  <%= f.input :current_sign_in_ip %>
  <%= error_span(@user[:current_sign_in_ip]) %>
  <%= f.input :last_sign_in_ip %>
  <%= error_span(@user[:last_sign_in_ip]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="list">
  <tr>
    <th>ID</th>
    <th>グループ名</th>
    <th>人数制限</th>
    <th>作成日時</th>
  </tr>
  <% @groups.each do |group| %>
    <tr>
      <%= content_tag :td, group.id %>
      <%= content_tag :td, (link_to group.name, group_path(group)) %>
      <%= content_tag :td, group.limit ? "#{group.limit}人" : "なし" %>
      <%= content_tag :td, group.created_at.strftime('%Y/%m/%d') %>
    </tr>
  <% end %>
</table>
<%= link_to('グループを新規作成', group_new_path) %>
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>